######### UPDATE ACCORDING TO YOUR PROJECT #########
# Name of firectory to putput Landscape Genetics files
landgen_dir: LandGen

# Exclude populations
exclude_pops:
  - SmT  # Example population to exclude, you can add more or leave empty if no populations should be excluded